- name: "web development"
  icon: /assets/img/web_development.svg
  delay: 0
- name: "theme integration"
  icon: /assets/img/wordpress.svg
  delay: 200
- name: "email design"
  icon: /assets/img/email.svg
  delay: 400
- name: "responsive redesign"
  icon: /assets/img/responsive.svg
  delay: 600
